# Generated by Django 2.1 on 2019-03-20 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precios', '0001_initial'),
        ('categorias', '0001_initial'),
        ('modelos', '0003_auto_20190319_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Modelo')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.Precio')),
            ],
        ),
    ]
