# Generated by Django 2.1 on 2019-03-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20190319_0317'),
        ('categorias', '0001_initial'),
        ('precios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precio',
            new_name='Producto',
        ),
    ]
