# Generated by Django 2.1 on 2019-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compra_detalle',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
