# Generated by Django 2.1 on 2019-03-23 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20190226_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
    ]
